### ISSUE TITLE
Callback arguments for onSuccess, onExit, onEvent

### ISSUE THREAD

**Issue by mkarazin** [plaid/react-native-plaid-link-sdk#18] opened 2019-12-16 03:09 UTC
I am attempting to migrate from the prior react-native library to this one. Currently using 2.0.0.

Using the newly exposed `openLink` method, I've noticed the `onSuccess` and `onExit` callbacks don't conform to the documentation and the `onEvent` event is never called. I haven't tried launching plaid link via any other method.

```
  import { openLink } from 'react-native-plaid-link-sdk';

  const config = {
    // Most properties ommitted
    onExit: (arg1, arg2) => { console.log('DEBUG:onExit', { arg1, arg2 }); },
    onEvent: (arg1, arg2) => { console.log('DEBUG:onEvent', { arg1, arg2 }); },
    onSuccess: (arg1, arg2) => { console.log('DEBUG:onSuccess', { arg1, arg2 }); },
  };

  openLink(config);
```

When looking at the debugger, I get for `onExit`:
<img width="296" alt="image" src="https://user-images.githubusercontent.com/906750/70876222-63dd2880-1f7e-11ea-908e-1c20ea648461.png">

And for `onSuccess`:
<img width="312" alt="image" src="https://user-images.githubusercontent.com/906750/70876294-abfc4b00-1f7e-11ea-8ddd-cd55114b19d0.png">

The documentation (and prior react-native plaid library) shows:
```
onSuccess: function(public_token, metadata),
onExit: function(error, metadata),
```

However my output always has the `metadata` first and no second argument. The `onSuccess` does return the `public_token`, but it is part of an object with `metadata` as well.

Is there something I'm missing? Or has the callback signatures changed and there is a different documentation source to look at?

**Comment by wkiefer** [comment] 2019-12-16 17:09
Thanks for the report.

This is the first official Plaid react-native SDK — which prior react-native library were you using? There were a few unofficial ones that we're hoping to have migrate to this officially supported library.

Instructions to get the `onEvent` callback are in the README:
https://github.com/plaid/react-native-plaid-link-sdk#to-receive-onevent-callbacks

**Comment by mkarazin** [comment] 2019-12-16 17:35
We were using https://github.com/plaid/plaid-link-examples/tree/master/react-native - which appears to have also been using the iOS SDK as this implementation is.

Besides the linking of the libraries being slightly different (yay for auto-linking!), our main code hardly changed.

Going from:
```
import PlaidLink from 'react-native-plaid-link';

// Config stuff omitted

PlaidLink.create(config);
PlaidLink.open();
```

To:
```
  import { openLink } from 'react-native-plaid-link-sdk';

  // Config stuff omittted

  openLink({ ...config, publicKey: config.key });
```

Besides needing to change the `key` prop to `publicKey`, it was a straight drop in replacement until I realized callbacks weren't working as they were before.

Regarding the onEvent stuff - I'll take a look at that later but for the purpose of this ticket we should probably just focus on the call back argument changes.

**Comment by wkiefer** [comment] 2019-12-16 17:46
Ahh great, makes sense. Thanks for the thorough reply.

I believe the proptype documentation is incorrect and we'll get that fixed up. thank you!

**Comment by mkarazin** [comment] 2019-12-18 16:51
Last night I was working on the Android side, using 2.0.3, and the `onSuccess` data is different for Android compared to iOS. It's more nested and the properties within are slightly different. For example, the `institution` object with `name` property doesn't exist but there is an `institution_name` property. Is this worthy of another ticket or should it be kept here? There was a ticket before https://github.com/plaid/react-native-plaid-link-sdk/issues/3 that is now closed and fixed in v2.0.1 however I'm seeing a lot of discrepancies between iOS and Android as well as this react-native library and plaid's other librarys/documentation.

**Comment by sandeepg1220** [comment] 2020-01-13 11:19
I'm also facing this issue while working on Android. data object is different for Android and iOS.

iOS response obj:
{
status: "connected"
link_session_id: "2c98455c-defa-472c-a783-94307c36e489"
institution:
institution_id: "ins_3"
name: "Chase"
__proto__: Object
accounts: Array(8)
0: {id: "nlR8eGow86fnKKNEA59ksE1kDXPyDEH6q4Pmz", mask: "0000", name: "Plaid Checking", subtype: "checking", type: "depository"}
1: {id: "bkDmrG4gmRCw44mzb5kPFKRdVol8VKtVpegva", mask: "1111", name: "Plaid Saving", subtype: "savings", type: "depository"}
2: {id: "mRM87Gpb86cPqqm7XrxzTNLzVlGbVNuLZaR36", mask: "2222", name: "Plaid CD", subtype: "cd", type: "depository"}
3: {id: "yNk8yXx586iljjV5q8RvHdMvWJVEWduyRBkvl", mask: "3333", name: "Plaid Credit Card", subtype: "credit card", type: "credit"}
4: {id: "91R9DapK9oudaa6Dwz5lULZRdapbdLcRN6zJw", mask: "4444", name: "Plaid Money Market", subtype: "money market", type: "depository"}
5: {id: "vdg8ywzA86iL44aqkgJjcxojePw1excWQda7A", mask: "5555", name: "Plaid IRA", subtype: "ira", type: "investment"}
6: {id: "Rdwx6aLoxlig55WDa74JuNw3gP4ygNuRVE71b", mask: "6666", name: "Plaid 401k", subtype: "401k", type: "investment"}
7: {id: "6Qn953Md9kfN33V4rp95TWyXZKwaZWig75jA3", mask: "7777", name: "Plaid Student Loan", subtype: "student", type: "loan"}
account: {id: null, mask: null, name: null, subtype: null, type: null}
request_id: "P8JLF10FuzKW9qO"
public_token: "public-sandbox-dd68c8ad-b1a2-4326-a9ee-b72086e2f736"
account_id: null
}

Android res obj:

	.	public_token: "public-sandbox-e28d17a4-1ed0-4a02-86e1-955674c9fe84" link_connection_metadata:
	.	raw_data: {public_token: "public-sandbox-e28d17a4-1ed0-4a02-86e1-955674c9fe84", link_session_id: "bb678173-963b-46b5-beb9-60960322a9e6", institution_name: "Chase", institution_id: "ins_3", accounts: "[{"_id":"8gKVrE8rkgfdqn1EwezBcbzdJkRVMXtwa7VXm","b…mber":"7777"},"type":"loan","subtype":"student"}]", …} link_session_id: "bb678173-963b-46b5-beb9-60960322a9e6" institution_name: "Chase" institution_id: "ins_3" accounts: Array(8)
	.	0:
	.	account_type: "depository" account_sub_type: "checking" account_number: "0000" account_name: "Plaid Checking" account_id: "8gKVrE8rkgfdqn1EwezBcbzdJkRVMXtwa7VXm" __proto__: Object 
	.	1: {account_type: "depository", account_sub_type: "savings", account_number: "1111", account_name: "Plaid Saving", account_id: "EJeEQDgQ5Jt59V1vknrEfaoyBmKAkjUXQ8PBm"} 2: {account_type: "depository", account_sub_type: "cd", account_number: "2222", account_name: "Plaid CD", account_id: "W3NgxDex53i5NvV7kEwnfK8BAVpjnXulM37bQ"} 3: {account_type: "credit", account_sub_type: "credit card", account_number: "3333", account_name: "Plaid Credit Card", account_id: "AJNbPEvPRJtZ94kbKnjvFQD8wl1PrgF1wLlpL"} 4: {account_type: "depository", account_sub_type: "money market", account_number: "4444", account_name: "Plaid Money Market", account_id: "GJZBMDEM5Jt5qV4wKx3Gf348aMN67XU19KXpx"} 5: {account_type: "investment", account_sub_type: "ira", account_number: "5555", account_name: "Plaid IRA", account_id: "nvE1rn3rzvcKZAaEG6wjfP1Gjeavb9c6k9N5l"} 6: {account_type: "investment", account_sub_type: "401k", account_number: "6666", account_name: "Plaid 401k", account_id: "bZEQMW9MJZc4pbNzG3D9FlRxZeq67WFVLn1kp"} 7: {account_type: "loan", account_sub_type: "student", account_number: "7777", account_name: "Plaid Student Loan", account_id: "mvyZKnBKkvcq8XJ7EDgnCGL6DmdRE8iLjenoD"} length: 8

**Comment by zsweigart** [comment] 2020-09-11 19:54
Closing this as duplicate of https://github.com/plaid/react-native-plaid-link-sdk/issues/47

**Closed by zsweigart** 2020-09-11 19:54 UTC
