### ISSUE TITLE
Android crash :  Unable to start activity ComponentInfo

### ISSUE THREAD

**Issue by uniquarkD** [plaid/react-native-plaid-link-sdk#152] opened 2020-07-03 08:04 UTC
Hi guys,

We've been getting the following error sometimes.

RN: 0.61.5
react-native-plaid-link-sdk: 4.0.0.  Android 2.0
    implementation project(':react-native-plaid-link-sdk')
    implementation 'com.plaid.link:sdk-core:2.0.0'
    implementation "com.squareup.okhttp3:okhttp:4.2.1"
    implementation "com.squareup.okhttp3:logging-interceptor:4.2.1"
    implementation "com.squareup.okhttp3:okhttp-urlconnection:4.2.1"

Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.coinseed/com.plaid.link.internal.LinkActivity}: kotlin.UninitializedPropertyAccessException: lateinit property component has not been initialized
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2419)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2479)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1347)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5421)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by JeroenMols** [comment] 2020-07-07 17:51
Hi @uniquarkD,

A possible explanation for this could be that our SDK isn't properly being initialized.
How are you initializing our SDK? Are you doing it in the Application class as we suggest in step two of our readme? https://github.com/plaid/react-native-plaid-link-sdk#2-add-plaidpackage-to-your-application

**Comment by JeroenMols** [comment] 2020-07-22 09:22
Hi @uniquarkD ,

We've found a potential root cause for this issue and will be putting out a new release to address this.
The issue we fixed is that our SDK wouldn't be properly reinitialized after process death, causing an error similar to yours.

I'll let you know when the fix is out, hopefully that will also address your issue.

Warm regards,
Jeroen

**Comment by nchase** [comment] 2020-07-27 17:03
Hi – just FYI, we're experiencing the same issue.

**Comment by JeroenMols** [comment] 2020-07-28 08:59
Hi @uniquarkD ,

We've just released a new SDK version, could you try upgrading and let us know whether you still see the errors or not?

- Plaid RN SDK version 5.0.0
- Plaid Android SDK version 2.1.2

Many thanks,
Jeroen

**Comment by nchase** [comment] 2020-07-29 15:11
@JeroenMols: what is different between this new version and 4.x.x? (Curious if there are any breaking changes to the API)

**Comment by zsweigart** [comment] 2020-08-17 22:39
Hi @nchase the main change is that `LinkConfiguration` with a `publicKey` is now deprecated in favor of LinkTokens.  See this article for details on the transition https://plaid.com/docs/link/transition-guide/

So 2.1.0+ is only compatible with 5.0.0+

**Comment by zsweigart** [comment] 2020-09-11 19:52
Closing this as it seems to be resolved.  Please reopen if the issue persists.

**Closed by zsweigart** 2020-09-11 19:52 UTC
Labels: android
