### ISSUE TITLE
HANDOFF is not being passed to usePlaidEmitter on iOS

### ISSUE THREAD

**Issue by jwoodmansey** [plaid/react-native-plaid-link-sdk#653] opened 2024-04-22 16:11 UTC
# The problem
HANDOFF is no longer being emitted after the link flow has completed successfully on iOS. 

# Environment

|                                                  |                                                                                  |
| -----------------------------| ----------------------------------------------- |
| Plaid Link React Native          | 11.8.0                                                                 |
| ReactNative Version               | 0.71.15                                                               |
| Occurs on Android                  | no                                                                     |
| Android OS Version                 | -                                                         |
| Android Devices/Emulators    | -                                                |
| Occurs on iOS                          | yes                                                                     |
| iOS Version                               | 17.2                                                                       |
| iOS Devices/Emulators            | iPhone 15 Pro Simulator                                                    |
| Link Session ID                         | c8c9eef9-64ac-4961-99f5-feb443c76cd8 |

# Steps to Reproduce
1. Listen for events with `usePlaidEmitter`
2. Call create/open flow
3. Continue through the plaid login flow

# Expected Result
HANDOFF should be emitted at the end of a successful flow but no longer is. 

I thought maybe we had an issue with using an outdated SDK but I've just updated to the latest and HANDOFF is still not being called. Android seems to work still. I also thought maybe we had a dependency breaking this on our side but I've gone back several months on our codebase and it still seems broken there.

**Comment by dtroupe-plaid** [comment] 2024-04-22 18:54
@jwoodmansey - Thanks for reporting. I have confirmed the issue and determined the root cause. I will post another update ASAP.

**Comment by jwoodmansey** [comment] 2024-04-22 19:24
> @jwoodmansey - Thanks for reporting. I have confirmed the issue and determined the root cause. I will post another update ASAP.

Thanks a lot :)

**Comment by dtroupe-plaid** [comment] 2024-04-22 22:19
@jwoodmansey I just released [11.8.1](https://github.com/plaid/react-native-plaid-link-sdk/releases/tag/v11.8.1) which should resolve this issue. 

I am going to close this issue, but please report back if you're still experiencing the issue after updating.

**Closed by dtroupe-plaid** 2024-04-22 22:19 UTC

**Comment by jwoodmansey** [comment] 2024-04-23 12:46
> @jwoodmansey I just released [11.8.1](https://github.com/plaid/react-native-plaid-link-sdk/releases/tag/v11.8.1) which should resolve this issue.
> 
> I am going to close this issue, but please report back if you're still experiencing the issue after updating.

Confirming this resolves our issue, thanks again!
