### ISSUE TITLE
Unable to debug why `open` function call is not working due to `usePlaidEmitter` throwing `NativeEventEmitter` error

### ISSUE THREAD

**Issue by daraghwlsh** [plaid/react-native-plaid-link-sdk#735] opened 2024-12-17 16:48 UTC
# The problem
Working on a personal project wanting to try out the SDK and ran into an issue. 

I get an error when attempting to debug why the `open` function call is not working in react-native with the `usePlaidEmitter` hook. I am getting nothing in my terminal logs when triggering the `open` function and so I needed to use the hook, however when the hook is being initialised, I get an error stating:
```
Invariant Violation: `new NativeEventEmitter()` requires a non-null argument.
```

This is in reference to this line in the `usePlaidEmitter` hook:
```
 const emitter = new NativeEventEmitter(RNLinksdk);
```
Where `RNLinksdk` must be null-ish for some reason. 

# Environment

|                                                  |                                                                                  |
| -----------------------------| ----------------------------------------------- |
| Plaid Link React Native          | ^11.13.3                                                                     |
| ReactNative Version               | 0.76.5                                                                        |
| Occurs on Android                  | not tested                                                                 |
| Android OS Version                 | not tested                                                              |
| Android Devices/Emulators    | not tested                                                 |
| Occurs on iOS                          | yes                                                                     |
| iOS Version                               | 16                                                                       |
| iOS Devices/Emulators            | iPhone 16 sim                                                    |

# Steps to Reproduce
## Link token creation
Created with the following in a sandbox environment: 
```
{
      user: {
        client_user_id: 'user-id-here',
        ...(email ? { email } : {}),
      },
      client_name: 'Money Transfer App',
      products: [Products.Auth],
      country_codes: [CountryCode.Us],
      language: 'en',
      required_if_supported_products: [Products.Identity],
      webhook: 'https://sample-web-hook.com',
      redirect_uri: redirectUri,
      auth: {
        automated_microdeposits_enabled: true,
      },
      ...(androidPackageName ? { android_package_name: androidPackageName } : {}),
    }
```
Where email, user-id-here, and redirectUri are dynamically passed (redirectUri is added to whitelist in sandbox environment)

## React Native setup
I have a hook which returns the screen data, the hook looks as follows:
```
import { useEffect, useRef, useState } from 'react'

import {
  create,
  open,
  usePlaidEmitter,
  dismissLink,
  type LinkSuccess,
  type LinkExit,
  type LinkOpenProps,
  LinkLogLevel,
  type LinkTokenConfiguration,
} from 'react-native-plaid-link-sdk'

import { useCreatePlaidLinkTokenMutation } from './custom-package/api-store'

export const useScreenData = () => {
  const [created, setCreated] = useState(false)
  const [createPlaidLinkToken, result] = useCreatePlaidLinkTokenMutation() 
  // gets link token successfully with createPlaidLinkToken

  const firstRender = useRef(true)

  usePlaidEmitter((event) => {
    console.log('Event: ', event)
  })

  const createPlaidLink = () =>
    createPlaidLinkToken({
      redirectUri: 'https://xxxxxxx.com/oauth-page.html',
    })

  const createLinkTokenConfiguration = (
    token: string,
    noLoadingState: boolean = false
  ): LinkTokenConfiguration => {
    return {
      token: token,
      // Hides native activity indicator if true.
      noLoadingState: noLoadingState,
    }
  }

  const createPlaidSession = (token: string) => {
    const tokenConfiguration = createLinkTokenConfiguration(token)
    create(tokenConfiguration)
    setCreated(true)
  }
  useEffect(() => {
    if (firstRender.current) {
      firstRender.current = false
      createPlaidLink()
    }
  }, [createPlaidLinkToken, result.data?.link_token])

  const createLinkOpenProps = (): LinkOpenProps => ({
    onSuccess: (success: LinkSuccess) => {
      // User was able to successfully link their account.
      console.log('Success: ', success)
    },
    onExit: (linkExit: LinkExit) => {
      // User exited Link session. There may or may not be an error depending on what occured.
      console.log('Exit: ', linkExit)
      dismissLink()
    },
    logLevel: LinkLogLevel.INFO,
  })

  const handleOpenLink = () => {
    const openProps = createLinkOpenProps()
    open(openProps)
  }

  return {
    loading: result.isLoading,
    createPlaidSession,
    openPlaidSession: handleOpenLink,
    token: result.data?.link_token,
    tokenCreated: created,
  }
}
```

On the screen there are then two buttons which call `createPlaidSession` and `openPlaidSession` respectfully. 

## What is happening
I can log the link_token successfully and know that it is present when it is passed to the `create` function. 

Once I trigger the `open` function nothing happens.
# Expected Result
## What did you expect to happen?
Flow to trigger
# Screenshots
If this is a visual bug a screenshot would be helpful.
N/A
# Logs
Any relevant logs from Android Logcat or the iOS console including stacktraces.
No logs that can be shared
# Code To Reproduce Issue 
1. Install iOS pods with `Pod 'Plaid'` in my podfile
2. Added `react-native-plaid-link-sdk` with `yarn add react-native-plaid-link-sdk`
3. Created hook as you see above
4. Trigger `create` and `open` functions in order
5. Nothing happens

**Comment by dtroupe-plaid** [comment] 2024-12-17 17:25
Hi @daraghwlsh ,

Thank you for submitting this issue! After reviewing your provided code, it seems that generating the link token is being handled within your React Native code. Since token generation does not occur within the React Native SDK, it should be excluded from the reported code example. This will help isolate any SDK-specific issues.

**Guidance on the Original Code**:

Token Creation Logic:
Since token generation happens outside the SDK, consider moving that logic to your backend or mocking it when creating a minimal reproducible example.

SDK Integration:
- Ensure `create()` is called only after a valid token is generated.
- Verify `open()` is triggered only after the session is successfully created.
- Consider simplifying the flow by ensuring no external dependencies interfere with SDK-related logic.

**Minimal Reproducible Example:**

Here’s a minimal working example based on the code you provided where Link successfully opens using a hardcoded token:

```typescript
import {useEffect, useState} from 'react';
import {
  create,
  open,
  usePlaidEmitter,
  dismissLink,
  type LinkSuccess,
  type LinkExit,
  type LinkOpenProps,
  LinkLogLevel,
  type LinkTokenConfiguration,
} from 'react-native-plaid-link-sdk';

export const useScreenData = () => {
  const [created, setCreated] = useState(false);
  const HARD_CODED_LINK_TOKEN = 'your-hardcoded-link-token';

  usePlaidEmitter(event => {
    console.log('Event: ', event);
  });

  const createLinkTokenConfiguration = (
    token: string,
    noLoadingState: boolean = false,
  ): LinkTokenConfiguration => {
    return {
      token: token,
      noLoadingState: noLoadingState,
    };
  };

  const createPlaidSession = (token: string) => {
    const tokenConfiguration = createLinkTokenConfiguration(token);
    create(tokenConfiguration);
    setCreated(true);
  };

  useEffect(() => {
    createPlaidSession(HARD_CODED_LINK_TOKEN);
  }, []);

  const createLinkOpenProps = (): LinkOpenProps => ({
    onSuccess: (success: LinkSuccess) => {
      console.log('Success: ', success);
    },
    onExit: (linkExit: LinkExit) => {
      console.log('Exit: ', linkExit);
      dismissLink();
    },
    logLevel: LinkLogLevel.INFO,
  });

  const handleOpenLink = () => {
    const openProps = createLinkOpenProps();
    open(openProps);
  };

  return {
    createPlaidSession,
    openPlaidSession: handleOpenLink,
    token: HARD_CODED_LINK_TOKEN,
    tokenCreated: created,
  };
};
```

and 

```typescript
import React from 'react';
import {View, Button, StyleSheet} from 'react-native';
import {useScreenData} from '../UseScreenData'; // Import the hook

const PlaidLinkScreen = () => {
  const {createPlaidSession, openPlaidSession} = useScreenData();

  return (
    <View style={styles.container}>
      <Button
        title="Create Plaid Session"
        onPress={() => createPlaidSession('link-sandbox-f6a0031c-82e0-4775-a261-7b85dced4d77')}
      />
      <Button title="Open Plaid Session" onPress={openPlaidSession} />
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 16,
  },
});

export default PlaidLinkScreen;
```

Note: I tested this code in the provided [example application](https://github.com/plaid/react-native-plaid-link-sdk/tree/master/example). 


If you’re still experiencing issues, please provide a minimal reproducible example similar to the code above. This will help us better understand the problem and provide more specific support.

If we don’t receive additional context, we may need to close this issue for now. Feel free to reopen it with more details.

**Closed by dtroupe-plaid** 2024-12-17 17:25 UTC

**Comment by daraghwlsh** [comment] 2024-12-18 09:16
Thank you for the quick response. I have attempted to strip down the solution and use a hard-coded token. However the same problems are occurring:
1. I cannot use `usePlaidEmitter` crashes my app with the same error message, so I cannot debug
2. Open function call does not trigger anything, despite the `create` function being called triggered

Is there an alternative method for debugging the function calls? As `usePlaidEmitter` is not currently possible. Thank you

**Comment by dtroupe-plaid** [comment] 2024-12-18 16:42
>I cannot use usePlaidEmitter crashes my app with the same error message, so I cannot debug

Did you run pod install in the `ios` directory? This issue hasn't been reported previously nor has the code related to this changed recently. 

>Is there an alternative method for debugging the function calls? As usePlaidEmitter is not currently possible

The use of this is not necessary to call `create` or `open`. You can add your own `console.log` code when you call any function.


>Open function call does not trigger anything, despite the create function being called triggered

Is onExit triggered? There could be an issue with the token you're using. Without more details I cannot reproduce this issue.
