### ISSUE TITLE
UI Problems with reCaptcha

### ISSUE THREAD

**Issue by agamadev** [plaid/react-native-plaid-link-sdk#219] opened 2020-10-10 16:10 UTC
# The problem

reCaptcha UI is not adapted to mobile screens. It happens quite often but not always: sometimes the reCaptcha looks centered on the same mobile device, sometimes it does not.

# Environment

|                        |  |
| ------------------------| ---------- |
| Plaid Link React Native          | 6.0.2-rc2                |
| ReactNative Version     | 0.63.2                |
| Occurs on Android             | yes                |
| Android OS Version                    | 9.0.0 (21)                |
| Android Devices/Emulators    | Pixel 2                |
| Occurs on iOS     | yes                |
| iOS Version           | 11                |
| iOS Devices/Emulators               | iPhone 11               |

# Steps to Reproduce

By running the app and be asked to validate the reCaptcha input.

# Expected Result

Preferably, the reCaptcha should look centered on the screen and users can easily click on the submit button.
Scroll on x axis is not ideal but still can work.

# Screenshots

![Screen Shot 2020-10-07 at 11 57 02 PM](https://user-images.githubusercontent.com/57379171/95659377-014dae00-0af7-11eb-836b-3078848e0ad8.png)
![Screen Shot 2020-10-08 at 12 01 51 AM](https://user-images.githubusercontent.com/57379171/95659379-04e13500-0af7-11eb-851e-23f5e8605b7e.png)

# Logs
Not relevant.

# Code To Reproduce Issue 

No code is necessary to reproduce the issue, however, this is the piece of code we have:

```javascript

<PlaidLink
     token={linkToken}
     onSuccess={data => handleSetPlaidReturn(data)}
>
     <Icon type={rigthAccionIcon.family} name={rigthAccionIcon.icon} style={styles.iconAdd} />
</PlaidLink>

```

**Comment by agamadev** [comment] 2020-10-16 00:07
Hi @JeroenMols - just to mention that it also happens on Android, not sure if it should also have the android label 😬

**Comment by JeroenMols** [comment] 2021-01-11 12:25
Thank you for filing this issue.

We are closing it on this project as this seems to be a Google recaptcha issue. Once google/recaptcha#334 is addressed, we will upgrade our backend and the fix should propagate to the React Native SDK. (so no upgrade should be necessary from your side)

Further we are also working on a more structural fix, but that will still take quite a bit of time to become available.

Duplicate of https://github.com/plaid/react-native-plaid-link-sdk/issues/183 and https://github.com/plaid/plaid-link-android/issues/80

**Closed by JeroenMols** 2021-01-11 12:25 UTC
Labels: android, ios
