### ISSUE TITLE
Building for android on 4.0.1: class file for androidx.drawerlayout.widget.DrawerLayout not found

### ISSUE THREAD

**Issue by drekembe** [plaid/react-native-plaid-link-sdk#296] opened 2020-12-22 10:28 UTC
# Background

We have a legacy mobile app that was previously running react native 0.59. It integrated Plaid via webview. RN 0.59.x now can't be deployed on the app store anymore, so we had to upgrade it to 0.60.6. I wanted to upgrade RN further, but due to other dependencies and decisions in the previous code, I was not able to.

We decided to use react-native-plaid-link-sdk to implement Plaid properly, but we had to use version 4.0.1, as it does not require RN 0.61. The README says that 4.0.1 is still active though and should use 2.0.0 or 2.1.0 version of com.plaid.link:sdk-core. Sounds good so far.

# The problem

When doing `yarn react-native run-android` in the repo to build and run the project on an android emulator, I get the following error:

```
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081
/Users/drek/rnplaid/rnExamplePlaidAndroid/android/app/src/main/java/com/rnexampleplaidandroid/MainActivity.java:5: error: cannot access DrawerLayout
public class MainActivity extends ReactActivity {
       ^
  class file for androidx.drawerlayout.widget.DrawerLayout not found
/Users/drek/rnplaid/rnExamplePlaidAndroid/android/app/src/main/java/com/rnexampleplaidandroid/MainActivity.java:11: error: method does not override or implement a method from a supertype
    @Override
    ^
2 errors
```

# Environment

|                        |  |
| ------------------------| ---------- |
| Plaid Link React Native          | 4.0.1                |
| ReactNative Version     | 0.60.6                |
| Occurs on Android             | yes                |
| Android OS Version                    | 9                |
| Android Link SDK Version.     | 2.1.0      |

I also tried version 2.0.0 of the Android Link SDK, but to no avail.

# Steps to Reproduce

I've created a minimal reproduction example: https://github.com/drekembe/rnExamplePlaidAndroid
To reproduce the error, do `yarn install` and then `yarn react-native run-android`. You might have to set $ANDROID_SDK_ROOT as well.

I know we're using a pretty old version of the SDK, however we don't have much of a choice right now. Thanks in advance for helping me solve this issue 🙏🏾

**Comment by JeroenMols** [comment] 2020-12-22 12:53
Hi @drekembe,

This isn't an issue with our SDK as we don't use `DrawerLayout`, so I think this might be something that react native implicitly relies on.

You can provide a version of `DrawerLayout` by adding the following to the `build.gradle file` in your `android/app` folder:

```
dependencies {
    implementation ("androidx.drawerlayout:drawerlayout:1.1.1")
}
```

And then solve the `duplicate class found ....` issues, most likely by [migrating your project fully to Androidx](https://developer.android.com/jetpack/androidx/migrate).

Best of luck!

**Comment by drekembe** [comment] 2020-12-22 14:31
Hey @JeroenMols, thanks for the quick reply and the helpful advice. I'll try your steps and hopefully that solves the issues. Do you have any idea why this `DrawerLayout` error only appears once I add the Plaid dependencies to my `build.gradle` and not before?

**Comment by JeroenMols** [comment] 2020-12-22 16:25
If you run `.gradlew :app:dependencies` from the android directory in your sample, it will print out all your dependencies and their transitive dependencies. When I do that, I can't see anyone pulling in the `DrawerLayout` dependency.

Furthermore, the error message also points to the `MainActivity` which doesn't contain any of our code. Hence that got me thinking react native creates a DrawerLayout under the hood to display debug information or something.

I'm not very sure why adding `Plaid` to your application causes this issue to surface. Can it be that`npm` or `yarn` resolves some other version of a dependency because Plaid is added?

**Comment by drekembe** [comment] 2020-12-23 11:29
Yeah, this issue is very weird. Thanks again for helping out.

There isn't any transitive dependency that's pulling in `DrawerLayout`. And even if there was, the reproduction repo is a fresh RN 0.60.6 install, which, from my understanding, is supposed to be set up to use AndroidX.

In the reproduction repo that I posted, the only non-dev dependencies in `package.json` are `react`, `react-native` and `react-native-plaid-link-sdk`. I have a feeling it's not an issue with JS dependencies because when I remove the Plaid dependencies from the `app/build.gradle` file (and the Plaid package inclusion in `MainApplication.java`), the project compiles.

**Comment by JeroenMols** [comment] 2021-01-05 10:20
Sorry for the premature close, I'm reopening this issue as I'm no longer sure this isn't caused by the Plaid Link SDK.

I've done some investigation and I've noticed that the compilation error in your sample project goes away when upgrading to the Plaid RN SDK `6.0.4`. Can you please try that on your end?

Note that we've never officially tested the combination of RN SDK `0.60.6` and Plaid RN SDK `6.0.4`!

Though we also haven't done anything to prevent interoperability between both. So please test thoroughly and use caution when going this route.

**Comment by drekembe** [comment] 2021-01-07 12:12
I tried upgrading to `6.0.4` and the build succeeded, but then I encountered a crash on app startup. I thought this might be a compatibility issue with our RN version, so I upgraded to RN `0.61.5` just to try (upgrading causes layout issues in our project, but that's not relevant here), and the crash still persisted. I created a separate issue for that.

Thanks for your continued help!

**Comment by JeroenMols** [comment] 2021-01-15 15:04
Closing this as both this and the follow up ticket got resolved: https://github.com/plaid/react-native-plaid-link-sdk/issues/300

**Closed by JeroenMols** 2021-01-15 15:04 UTC
Labels: android
