### ISSUE TITLE
createWithLinkPublicKeyConfiguration returns null 

### ISSUE THREAD

**Issue by devshorts** [plaid/react-native-plaid-link-sdk#225] opened 2020-10-16 22:52 UTC
# The problem

I have recently upgraded to plaid link `6.0.2` and am using the legacy public key configuration (until we can migrate over).  I am getting an error when trying to open plaid (using `openLink`) which says this:

```
Printing description of error:
{
    code = "ECOM.PLAID.LINK3";
    domain = "com.plaid.link";
    message = "The operation couldn\U2019t be completed. (com.plaid.link error 3.)";
    nativeStackIOS = (
	0   App                                0x00000001093a14c7 RCTJSErrorFromCodeMessageAndNSError + 135
	1   App                                0x00000001093a13f3 RCTJSErrorFromNSError + 275
	2   App                                0x000000010971a432 -[RNLinksdk open:] + 770
	3   CoreFoundation                      0x00007fff23e44dec __invoking___ + 140
	4   CoreFoundation                      0x00007fff23e41fd1 -[NSInvocation invoke] + 321
	5   CoreFoundation                      0x00007fff23e422a4 -[NSInvocation invokeWithTarget:] + 68
	6   App                                0x000000010931f074 -[RCTModuleMethod invokeWithBridge:module:arguments:] + 2660
	7   App                                0x0000000109323241 _ZN8facebook5reactL11invokeInnerEP9RCTBridgeP13RCTModuleDatajRKN5folly7dynamicE + 801
	8   App                                0x0000000109322d16 _ZZN8facebook5react15RCTNativeModule6invokeEjON5folly7dynamicEiENK3$_0clEv + 134
	9   App                                0x0000000109322c7c ___ZN8facebook5react15RCTNativeModule6invokeEjON5folly7dynamicEi_block_invoke + 28
	10  libdispatch.dylib                   0x00007fff520db951 _dispatch_call_block_and_release + 12
	11  libdispatch.dylib                   0x00007fff520dc8cb _dispatch_client_callout + 8
	12  libdispatch.dylib                   0x00007fff520e8cdb _dispatch_main_queue_callback_4CF + 1042
	13  CoreFoundation                      0x00007fff23da1869 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	14  CoreFoundation                      0x00007fff23d9c3b9 __CFRunLoopRun + 2041
	15  CoreFoundation                      0x00007fff23d9b8a4 CFRunLoopRunSpecific + 404
	16  GraphicsServices                    0x00007fff38c05bbe GSEventRunModal + 139
	17  UIKitCore                           0x00007fff49372964 UIApplicationMain + 1605
	18  App                                0x0000000108959240 main + 112
	19  libdyld.dylib                       0x00007fff5211c1fd start + 1
	20  ???                                 0x0000000000000001 0x0 + 1
);
    userInfo =     {
        message = "Swift.WritableKeyPath<LinkKit.LinkPublicKeyConfiguration, Swift.String> must be a properly formatted, non-empty string";
    };
}
```

Which I've managed to debug into and see that the `self.linkHandler` is not getting assigned even after calling into it

![image](https://user-images.githubusercontent.com/1799346/96320239-b506e000-0fc6-11eb-9fae-5772cc0a904d.png)

Since the [linkit dependency](https://github.com/plaid/plaid-link-ios/tree/f7226de98eb6750889879ac0f046feda82d8ddb5/LinkKit.framework) looks to be a distributed static library I can't seem to debug much further to find out whats going on. 

From the react native side of things I'm calling into it like this:

```
openLink({
    publicKey: "...",
    clientName: "...",
    env: 'sandbox',
    product: ['auth'],
    webviewRedirectUri: "...",
    onSuccess: (success) => { ... }
})
```

When I was using `"react-native-plaid-link-sdk": "^3.0.1",` it worked fine, which used the plaid dependency of 
```
  - Plaid (1.1.27)
``` 
in the podfile (I am using `Plaid (2.0.3)` now)

I recently had to use_frameworks! in the pod file  like so

```
use_frameworks! :linkage => :static
```
and I'm hoping that this isn't the cause of what I'm seeing (as we needed that for another library integration)

Anyways, this is well beyond my normal expertise... so hope this is enough info to help shed some light or maybe tell me I'm doing a dumb and this is a non issue somehow :p 

# Environment

|                        |  |
| ------------------------| ---------- |
| Plaid Link React Native          | e.g. 6.0.2                |
| ReactNative Version     | e.g. 0.61.5                |
| Occurs on iOS     | e.g. yes                |
| iOS Version           | e.g. 11                |
| iOS Devices/Emulators               | e.g. iPhone X                |

**Comment by devshorts** [comment] 2020-10-20 18:40
For what its worth I did the v2 link migration and this error went away. That said, it doesn't seem that the legacy public key flow works with the 2.x Plaid pod

**Comment by pladaub** [comment] 2020-11-02 19:08
Hi, thanks for filing this issue. For legacy public key configurations, the `language` prop is required to be set to a non-empty string value. Upon review, our validation code isn't outputting the correct error message here. This will be addressed by a future release of the underlying iOS SDK.

**Comment by pladaub** [comment] 2021-01-21 17:08
Closing the issue as the code is working as intended, and the better error messaging has landed.

**Closed by pladaub** 2021-01-21 17:08 UTC
Labels: ios
