### ISSUE TITLE
Google reCaptcha puzzle is not completely visible

### ISSUE THREAD

**Issue by Vadim7394** [plaid/react-native-plaid-link-sdk#183] opened 2020-09-17 08:27 UTC
Phone: Samsung Galaxy A10 with a 6.2-inch screen

![image](https://user-images.githubusercontent.com/19637034/93442578-1b71e300-f8e1-11ea-82ab-590b92734118.png)
![image](https://user-images.githubusercontent.com/19637034/93442716-262c7800-f8e1-11ea-8f67-1f42e436adec.png)

**Comment by JeroenMols** [comment] 2020-09-28 09:03
Hi @Vadim7394  thanks for this report. The current iteration of the SDK uses a webview to display Link. We have run into several issues with recaptcha being cutoff in webviews and we have opened an issue on the Google recaptcha project google/recaptcha#334.

We are closing it on this project as this seems to be a Google recaptcha issue. Once google/recaptcha#334 is addressed, we will upgrade our backend and the fix should propagate to the react native SDK.

Also a duplicate of https://github.com/plaid/plaid-link-android/issues/80

**Closed by JeroenMols** 2020-09-28 09:03 UTC

**Comment by Tan-Aki** [comment] 2022-01-07 15:41
For me, this issue seems to only occur when I start the page in full screen, and then resize it to mobile with the chrome devtools device toolbar.

If I start the page in mobile, the image selection is displayed properly and is centered.

So, to me, it's a non-issue after all.
