### ISSUE TITLE
Application crash in android when long press in input text - Android

### ISSUE THREAD

**Issue by kanji-keraliya** [plaid/react-native-plaid-link-sdk#38] opened 2020-01-11 05:19 UTC
Hello @wkiefer @zsweigart 

I have one issue in plaid, after adding username in plaid windows I tried to copy that username but when I long press on that text input application crashed.

Can you help me, how to prevent application crash in any condition?

**Comment by zsweigart** [comment] 2020-02-24 20:07
Hi @kanji-keraliya thanks for the report, we will investigate with the latest 3.0 release

**Comment by zsweigart** [comment] 2020-03-10 20:58
Hi @kanji-keraliya we have been unable to reproduce, can you provide more information including:
- What device are you using?
- What OS version is it running?

**Comment by zsweigart** [comment] 2020-03-17 18:10
Closing as cannot reproduce

**Closed by zsweigart** 2020-03-17 18:10 UTC
Labels: android
