### ISSUE TITLE
openLink doesn't work on Android 8.1 device

### ISSUE THREAD

**Issue by Gentlee** [plaid/react-native-plaid-link-sdk#352] opened 2021-03-25 15:16 UTC
# The problem

I got a very strange error when trying to open link on Android device. On emulator (Android 10) and iOS simulator it works.
Everything is good with my connection, all other requests are executed.

The only thing i did to make the app not crash on startup is to keep `implementation 'com.squareup.okhttp3:okhttp-urlconnection:4.9.0'` in build gradle as mentioned [here](https://github.com/plaid/react-native-plaid-link-sdk/issues/351).

# Environment

|                        |  |
| ------------------------| ---------- |
| Plaid Link React Native          | 7.0.2                |
| ReactNative Version     | 0.63.4                |
| Occurs on Android             | yes                |
| Android OS Version                    | 8.1.0              |
| Android Devices/Emulators    | e.g. Nexus 5x device                |

# Screenshots

![Screenshot 2021-03-25 at 18 01 50](https://user-images.githubusercontent.com/2361140/112496339-b6b6aa00-8d95-11eb-9ee6-76bdb4442312.png)

# Logs
```
E/unknown:ReactContextBaseJavaModule: Unhandled SoftException
    java.lang.RuntimeException: Catalyst Instance has already disappeared: requested by WebSocketModule
        at com.facebook.react.bridge.ReactContextBaseJavaModule.getReactApplicationContextIfActiveOrWarn(ReactContextBaseJavaModule.java:67)
        at com.facebook.react.modules.websocket.WebSocketModule.sendEvent(WebSocketModule.java:62)
        at com.facebook.react.modules.websocket.WebSocketModule.access$100(WebSocketModule.java:40)
        at com.facebook.react.modules.websocket.WebSocketModule$1.onMessage(WebSocketModule.java:190)
        at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.kt:333)
        at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.kt:245)
        at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.kt:106)
        at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.kt:293)
        at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:195)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
```

# Code To Reproduce Issue 
```
openLink({
  publicKeyConfig: {
    clientName: "example"
    countryCodes: ["US"]
    environment: "sandbox"
    language: "en"
    products: ["auth"]
    publicKey: "example"
  },
  onSuccess,
  onExit,
});

**Comment by zsweigart** [comment] 2021-04-05 17:02
Hi @Gentlee we have seen issues with certain emulators failing due to buggy chromium versions.  Could you try updating the version on chromium on your emulator to see if the issue persists on the 8.1 emulator?

**Comment by Gentlee** [comment] 2021-04-05 21:05
@zsweigart I'm using device, not emulator.

**Comment by zsweigart** [comment] 2021-04-08 21:50
I see now. That is expected when okhttp3 version 4+ isn't present.  React-Native bundles in okhttp3 version 3, but our sdk should be providing 4, this seems to be a duplicate of the other issue https://github.com/plaid/react-native-plaid-link-sdk/issues/351. I'll respond over there

**Comment by zsweigart** [comment] 2021-05-03 13:28
Adding `implementation 'com.squareup.okhttp3:okhttp-urlconnection:4.9.0'` #351 

Closing this one as well

**Closed by zsweigart** 2021-05-03 13:28 UTC
Labels: android

**Comment by Gentlee** [comment] 2021-05-03 14:17
@zsweigart it is not duplicate, it is another issue.
