### ISSUE TITLE
linkCustomizationName not working with latest version

### ISSUE THREAD

**Issue by walterholohan** [plaid/react-native-plaid-link-sdk#279] opened 2020-12-02 16:59 UTC
# The problem

I just upgraded this library to version 6.0.4 and everything worked ok except for `linkCustomizationName` when using openLink on iOS. We use multiple customization configs to display different screens per config. 

# Environment

|                        |  |
| ------------------------| ---------- |
| Plaid Link React Native          | 6.0.4                |
| ReactNative Version     | 0.62.2              |
| Occurs on iOS     | yes               |
| iOS Version           | 13.6             |
| iOS Devices/Emulators               | iPhone 11                |

# Steps to Reproduce

Pass the following config into the openLink() function

```
openLink(
{
    clientName: 'ClientName',
    publicKey: Config.PLAID_PUBLIC_KEY,
    env: 'sandbox',
    product: Config.PLAID_PRODUCTS.split(','),
    accountSubtypes: {
      depository: ['checking', 'savings'],
    },
    linkCustomizationName: Config.PLAID_LINK_CUSTOMIZATION_NAME,
    countryCodes: ['US'],
    language: 'en',
    onSuccess: onSuccess,
    onEvent: onEvent,
    onExit: onExit,
  }
)
```

# Expected Result
I should be able to see the customized flow for the config name that is passed to `linkCustomizationName`

**Comment by pladaub** [comment] 2020-12-07 19:52
What version did you update to 6.0.4 from? Curious where you last saw this working

**Comment by pladaub** [comment] 2021-01-21 11:09
I've validated the report, the issue is with the underlying LinkKit SDK. A fix will be present in our next LinkKit release. Thanks for the report!

**Comment by pladaub** [comment] 2021-02-11 20:15
Hi, this has been fixed in RN v7-rc4 and is available now

**Closed by pladaub** 2021-02-11 20:15 UTC
Labels: ios

**Comment by walterholohan** [comment] 2021-02-16 09:23
Cheers @pladaub, do you have any update on when RN v7 is going to be released?
