### ISSUE TITLE
Android 10 crash when try to open plaid widget

### ISSUE THREAD

**Issue by Mactub07** [plaid/react-native-plaid-link-sdk#40] opened 2020-01-11 14:11 UTC
given that:
OS: Android 10
device: Pixel 2

issue: crash on OS android 10 when try to open plaid widget;
Plaid SDK : 'com.plaid.link:sdk-core:0.3.2'
react-native-plaid-sdk : 2.0.4

it happens only on android 10, on Android 8 it works normally

react-native-info:
System:
    OS: macOS 10.15.1
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Memory: 226.15 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 13.3.0 - /usr/local/bin/node
    Yarn: 1.19.2 - /usr/local/bin/yarn
    npm: 6.13.2 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 24, 27, 28, 29
      Build Tools: 27.0.3, 28.0.3, 29.0.2
      System Images: android-24 | Intel x86 Atom, android-24 | Intel x86 Atom_64, android-24 | Google APIs Intel x86 Atom, android-27 | Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom
  IDEs:
    Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
  npmPackages:
    react: ^16.12.0 => 16.12.0 
    react-native: 0.61.4 => 0.61.4 
  npmGlobalPackages:
    create-react-native-app: 1.0.0
    react-native-cli: 2.0.1
    react-native-git-upgrade: 0.2.7
    react-native-rename: 2.2.2
    react-native-vector-icons: 4.0.0

Stack trace:
android.security.KeyStore.getInvalidKeyException KeyStore.java:1309
android.security.KeyStore.getInvalidKeyException KeyStore.java:1402
android.security.keystore.KeyStoreCryptoOperationUtils.getInvalidKeyExceptionForInit KeyStoreCryptoOperationUtils.java:54
android.security.keystore.KeyStoreCryptoOperationUtils.getExceptionForCipherInit KeyStoreCryptoOperationUtils.java:89
android.security.keystore.AndroidKeyStoreCipherSpiBase.ensureKeystoreOperationInitialized AndroidKeyStoreCipherSpiBase.java:265
android.security.keystore.AndroidKeyStoreCipherSpiBase.engineInit AndroidKeyStoreCipherSpiBase.java:109
javax.crypto.Cipher.tryTransformWithProvider Cipher.java:2984
javax.crypto.Cipher.tryCombinations Cipher.java:2877
javax.crypto.Cipher$SpiAndProviderUpdater.updateAndGetSpiAndProvider Cipher.java:2796
javax.crypto.Cipher.chooseProvider Cipher.java:773
javax.crypto.Cipher.init Cipher.java:1143
javax.crypto.Cipher.init Cipher.java:1084
com.plaid.storage.PlaidKeystore.rsaDecrypt PlaidKeystore.kt:249
com.plaid.storage.PlaidKeystore.getSecretKey PlaidKeystore.kt:289
com.plaid.storage.PlaidKeystore.encrypt$storage_release PlaidKeystore.kt:95
com.plaid.storage.PlaidSecureStorage.saveData PlaidSecureStorage.kt:74
com.plaid.analytics.PlaidAnalyticsImpl.loadIdentity PlaidAnalyticsImpl.kt:158
com.plaid.analytics.PlaidAnalyticsImpl.getUserId PlaidAnalyticsImpl.kt:45
com.plaid.analytics.PlaidAnalyticsImpl.track PlaidAnalyticsImpl.kt:90
com.plaid.analytics.PlaidAnalyticsImpl.track PlaidAnalyticsImpl.kt:81
com.plaid.link.LinkActivity.onResume LinkActivity.kt:81
android.app.Instrumentation.callActivityOnResume Instrumentation.java:1453
android.app.Activity.performResume Activity.java:7962
android.app.ActivityThread.performResumeActivity ActivityThread.java:4195
android.app.ActivityThread.handleResumeActivity ActivityThread.java:4237
android.app.servertransaction.ResumeActivityItem.execute ResumeActivityItem.java:52
android.app.servertransaction.TransactionExecutor.executeLifecycleState TransactionExecutor.java:176
android.app.servertransaction.TransactionExecutor.execute TransactionExecutor.java:97
android.app.ActivityThread$H.handleMessage ActivityThread.java:2016
android.os.Handler.dispatchMessage Handler.java:107
android.os.Looper.loop Looper.java:214
android.app.ActivityThread.main ActivityThread.java:7356
java.lang.reflect.Method.invoke Method.java
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run RuntimeInit.java:492
com.android.internal.os.ZygoteInit.main ZygoteInit.java:930

additionally:
android.app.ActivityThread.performResumeActivity ActivityThread.java:4205
android.app.ActivityThread.handleResumeActivity ActivityThread.java:4237
android.app.servertransaction.ResumeActivityItem.execute ResumeActivityItem.java:52
android.app.servertransaction.TransactionExecutor.executeLifecycleState TransactionExecutor.java:176
android.app.servertransaction.TransactionExecutor.execute TransactionExecutor.java:97
android.app.ActivityThread$H.handleMessage ActivityThread.java:2016
android.os.Handler.dispatchMessage Handler.java:107
android.os.Looper.loop Looper.java:214
android.app.ActivityThread.main ActivityThread.java:7356
java.lang.reflect.Method.invoke Method.java
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run RuntimeInit.java:492
com.android.internal.os.ZygoteInit.main ZygoteInit.java:930

**Comment by zsweigart** [comment] 2020-02-24 20:10
Hi @Mactub07 thanks for the report, we will investigate on the latest release 3.0

**Comment by zsweigart** [comment] 2020-03-07 18:23
Hi @Mactub07 could you please update to the latest release

**Comment by zsweigart** [comment] 2020-03-12 14:39
Are there any steps to reproduce?

**Comment by Mactub07** [comment] 2020-03-21 06:34
Upgraded library , crash aren't reproduced

**Comment by miguel-martinez-0** [comment] 2020-03-23 16:04
> Upgraded library , crash aren't reproduced

What is you current version now?

**Comment by JeroenMols** [comment] 2020-03-23 16:43
@Mactub07 thanks for retesting!

In the past releases we've made quite some improvements to our secure storage code. Since you are currently no longer able to reproduce, I suggest to close this issue. Please don't hesitate to contact us when this happens again.

**Closed** 2020-03-23 17:04 UTC
Labels: android

**Comment by Mactub07** [comment] 2020-03-25 17:19
@miguel-martinez-0 
"react-native-plaid-link-sdk": "^3.0.1",
