### ISSUE TITLE
On Android input text is cut

### ISSUE THREAD

**Issue by beqramo** [plaid/react-native-plaid-link-sdk#402] opened 2021-07-30 07:47 UTC
# The problem
On android input text isn't shown properly(see attached video)
# Environment

|                        |  |
| ------------------------| ---------- |
| Plaid Link React Native          |  ^7.0.7              |
| ReactNative Version     |  0.64.1                |
| Occurs on Android             |  yes                |
| Android OS Version                    |  10.0.0               |
| Android Devices/Emulators               | Nokia 2.1          |

| Occurs on iOS     | e.g. no                |
| iOS Version           | e.g. 11                |

# Steps to Reproduce

https://user-images.githubusercontent.com/40486471/127619543-fcf061af-dba5-40ba-9540-62be4db96ea6.mp4

**Comment by bjjeong** [comment] 2021-08-04 15:31
looks to be a duplicate of https://github.com/plaid/react-native-plaid-link-sdk/issues/382

**Comment by beqramo** [comment] 2021-08-05 05:35
Hi,
No, there is a scroll, but the text is cut inside the input, they are different.

**Comment by amytang0** [comment] 2021-08-05 19:50
Is the font setting set to something larger than the default on this device?

**Comment by beqramo** [comment] 2021-08-05 19:55
Hi,
I haven't changed any font or even there is no font scaling enabled on device

**Comment by amytang0** [comment] 2021-08-09 20:14
Thank you for the flag, we are working to resolve this

**Comment by amytang0** [comment] 2021-12-13 21:23
![adbscreen](https://user-images.githubusercontent.com/863461/145890887-80a1c4c8-c1c0-408b-a7f6-ee37f42aeb54.png)

Issue is now resolved; please re-open if there is a device/configuration where you see this reproing

**Closed by amytang0** 2021-12-13 21:23 UTC
