### ISSUE TITLE
Application crash in android when system back button

### ISSUE THREAD

**Issue by kanji-keraliya** [plaid/react-native-plaid-link-sdk#29] opened 2019-12-26 06:52 UTC
Hello,

Application crash in android when press system back button after open plaid window

`2019-12-26 12:34:04.497 7040-7040/com.rnplaidexample E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.rnplaidexample, PID: 7040
    java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=101, result=0, data=null} to activity {com.rnplaidexample/com.rnplaidexample.MainActivity}: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter data
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4323)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4366)
        at android.app.ActivityThread.-wrap19(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1649)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6540)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
     Caused by: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter data
        at com.plaid.PlaidModule.onActivityResult(Unknown Source:7)
        at com.facebook.react.bridge.ReactContext.onActivityResult(ReactContext.java:275)
        at com.facebook.react.ReactInstanceManager.onActivityResult(ReactInstanceManager.java:703)
        at com.facebook.react.ReactDelegate.onActivityResult(ReactDelegate.java:89)
        at com.facebook.react.ReactActivityDelegate.onActivityResult(ReactActivityDelegate.java:110)
        at com.facebook.react.ReactActivity.onActivityResult(ReactActivity.java:67)
        at android.app.Activity.dispatchActivityResult(Activity.java:7237)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4319)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4366) 
        at android.app.ActivityThread.-wrap19(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1649) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6540) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) `

You can find sample example code here.

https://github.com/kanji-keraliya/RNPlaidExample/tree/0e6d833ff3928ff4d0dcfad646ca647f8fb25f33

Can anyone help me to integrate official plaid in react native application.

Thank

**Comment by edo1493** [comment] 2019-12-29 08:19
I have the same issue as well. :)

**Comment by zsweigart** [comment] 2020-01-08 16:50
Thanks for the report, I have been able to reproduce so we will look into it.

**Comment by ShahidAli786** [comment] 2020-02-18 12:09
I have the same issue, any solutions?

**Comment by ShahidAli786** [comment] 2020-02-18 13:23
I have solve this by adding following changes in  node_modules/react-native-plaid-link-sdk/android/src/main/java/com/plaid/PlaidModule.kt.

`  override fun onActivityResult(
    activity: Activity,
    requestCode: Int,
    resultCode: Int,
    data: Intent?
  ) {
    val result = WritableNativeMap()

    result.putInt(RESULT_CODE, resultCode)

    if (requestCode == LINK_REQUEST_CODE) {
      if (resultCode == Plaid.RESULT_SUCCESS) {
        val item = data!!.getParcelableExtra(Plaid.LINK_RESULT) as LinkConnection
        result.putMap(DATA, convertJsonToMap(JSONObject(snakeCaseGson.toJson(item))))
      } else if (resultCode == Plaid.RESULT_CANCELLED) {
        val cancellation = data!!.getParcelableExtra(Plaid.LINK_RESULT) as LinkCancellation
        result.putMap(DATA, convertJsonToMap(JSONObject(snakeCaseGson.toJson(cancellation))))
      } else if (resultCode == Plaid.RESULT_EXIT) {
        val error = data!!.getParcelableExtra(Plaid.LINK_RESULT) as PlaidApiError
        result.putMap(DATA, convertJsonToMap(JSONObject(snakeCaseGson.toJson(error))))
      } else if (resultCode == Plaid.RESULT_EXCEPTION) {
        val exception = data!!.getSerializableExtra(Plaid.LINK_RESULT) as Exception
        val map = WritableNativeMap()
        map.putString("class", exception.javaClass.name)
        map.putString("message", exception.message)
        result.putMap(DATA, map)
      }
      this.callback?.invoke(result)
    } else {
      if (data!!.extras != null) {
        result.putMap(DATA, Arguments.makeNativeMap(data!!.extras))
      }
      this.callback?.invoke(result)
    }
  }`

**Comment by mikeislearning** [comment] 2020-02-21 15:51
@ShahidAli786 Did you want to make a pull request with your fix?

**Comment by zsweigart** [comment] 2020-02-24 20:02
Hi @ShahidAli786 and @mikeislearning we have addressed these in the latest release 3.0 which includes our first non-beta Android sdk release.

**Comment by zsweigart** [comment] 2020-02-26 18:34
Please let us know if this resolves your issue (sorry for the early close)

**Comment by JeroenMols** [comment] 2020-03-18 07:08
@kanji-keraliya can you please upgrade to 3.0.1 and let us know if your issue is fixed or not?
That enables us to close this ticket or look into alternative solutions.

**Comment by JeroenMols** [comment] 2020-04-09 11:55
Closing this issue due to a month of inactivity, should the problem still persist don't hesitate to reopen or file a new issue.

**Closed by JeroenMols** 2020-04-09 11:55 UTC
Labels: android
