### ISSUE TITLE
[Android] There is no scroll on Enter credentials screen when keyboard opened

### ISSUE THREAD

**Issue by Mactub07** [plaid/react-native-plaid-link-sdk#382] opened 2021-05-13 13:29 UTC
# The problem

Problem is when you try to focus password input there is no posibility to do it on small devices like Google Pixel 2. Keyboard overflows input and it can't be scrolled (see screen attached) 

# Environment

|                        |  |
| ------------------------| ---------- |
| Plaid Link React Native          | 7.0.5               |
| ReactNative Version     | 0.63.4                |
| Occurs on Android             |  yes                |
| Android OS Version                    | 11               |
| Android Devices/Emulators    |  Pixel 2 physical                |

# Expected Result
user shoud be able to see password input when keyboard opened on small devices

![IMG_0176](https://user-images.githubusercontent.com/13048119/118132579-83dd7980-b408-11eb-925c-0105a24eac9c.JPG)

**Comment by serratus** [comment] 2021-05-13 17:41
@Mactub07 We are running into the same issue. We tried all different versions of `7`, but no luck on any.

We moved from our own web-view implementation to `react-native-plaid-link-sdk` in hope to reduce the problems with screen loadings and hand-offs. Also because of the mandatory use of the `link-token`s.

This is a pretty big blocker us. Is anyone aware of a workaround?

### How to reproduce

1. Clone the repository
2. build the `example` app (Android)
3. Navigate to the credentials screen
4. Try to scroll

### iOS

Works fine on iOS, only Android seems to have this issue.

**Comment by amytang0** [comment] 2021-05-13 19:35
Hi, we are looking into this. In the meantime, the password input can be accessed by either 1. pressing enter from the username input or 2. pressing back to hide the keyboard, then clicking on the password input.

Thank you for the flag!

**Comment by amytang0** [comment] 2021-08-05 20:04
Hi we are planing to release another RN version with the updated Android version, but in the meantime, could you try adding to your `android/app/build.gradle` and see if that resolves the issue?
```
implementation("com.plaid.link:sdk-core:3.4.1") {
    force true
}
```

**Comment by amytang0** [comment] 2021-12-13 21:24
This is resolved in the latest version, please re-open if the issue still recurs

**Closed by amytang0** 2021-12-13 21:24 UTC
