### ISSUE TITLE
Android crash in com.plaid.PlaidModule.onActivityResult

### ISSUE THREAD

**Issue by nchase** [plaid/react-native-plaid-link-sdk#166] opened 2020-07-29 15:09 UTC
Hi folks – we're seeing this crash with `react-native-plaid-link-sdk` v4.0.1

```
java.lang.RuntimeException: 
  at android.app.ActivityThread.deliverResults (ActivityThread.java:5255)
  at android.app.ActivityThread.handleSendResult (ActivityThread.java:5296)
  at android.app.servertransaction.ActivityResultItem.execute (ActivityResultItem.java:51)
  at android.app.servertransaction.TransactionExecutor.executeCallbacks (TransactionExecutor.java:135)
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:95)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2229)
  at android.os.Handler.dispatchMessage (Handler.java:107)
  at android.os.Looper.loop (Looper.java:237)
  at android.app.ActivityThread.main (ActivityThread.java:8034)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:493)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1076)

Caused by: java.lang.RuntimeException: 
  at com.facebook.react.bridge.CallbackImpl.invoke (CallbackImpl.java:26)
  at com.plaid.PlaidModule.onActivityResult (PlaidModule.kt:208)
  at com.facebook.react.bridge.ReactContext.onActivityResult (ReactContext.java:288)
  at com.facebook.react.ReactInstanceManager.onActivityResult (ReactInstanceManager.java:738)
  at com.facebook.react.ReactDelegate.onActivityResult (ReactDelegate.java:90)
  at com.facebook.react.ReactActivityDelegate.onActivityResult (ReactActivityDelegate.java:112)
  at com.facebook.react.ReactActivity.onActivityResult (ReactActivity.java:68)
  at android.app.Activity.dispatchActivityResult (Activity.java:8294)
  at android.app.ActivityThread.deliverResults (ActivityThread.java:5248)
```

**Comment by zsweigart** [comment] 2020-08-04 22:58
hi @nchase Thanks for the report.  Can you provide more information on the crash:

- What configuration are you using (omit your keys)
- What are the steps to reproduce?
- What device(s) does this occur on?
- What OS version(s)?

Thanks.

**Comment by nchase** [comment] 2020-08-14 17:53
Hi @zsweigart:

1. What part of our config are you interested in? I can share if you give more specifics.
2. It's currently unclear how to reproduce this. This is happening for some of our users, but we haven't had luck reproducing it ourselves, yet.
3. It's happening across a variety of Android devices (e.g. SM-G970U and Pixel)
4. Android 9 and 10

One thing that might be particularly interesting is that the stacktrace for this crash also includes this:

```
java.lang.RuntimeException: Illegal callback invocation from native module. This callback type only permits a single invocation from native code.
```

That part of the stacktrace suggests that your [`onActivityResult`](https://github.com/plaid/react-native-plaid-link-sdk/blob/d8ced9a8a2faca86c15e2385b3eb5b17ec64c883/android/src/main/java/com/plaid/PlaidModule.kt#L216-L252) function is getting called twice?

**Comment by zsweigart** [comment] 2020-08-17 18:23
Hi @nchase thanks for all the info for 1. the full configuration from the `<PlaidLink` component would be helpful. 

One thing that would be worth checking is if your callback is being called multiple times.  You may have to refresh the callback - https://github.com/facebook/react-native/issues/13595

**Comment by zsweigart** [comment] 2020-08-18 17:40
Hi @nchase are you using 4.0.1 with android 2.1.0+? If so you'll need to use 5.0.0

We'll be adding a compatibility table to make this clearer. https://github.com/plaid/react-native-plaid-link-sdk/pull/170

**Comment by nchase** [comment] 2020-08-23 18:06
@zsweigart yeah, looks like we are using 4.0.1 alongside of the latest android SDK. We'll upgrade. 

Additionally we'll check to see if we're calling `onActivityResult` ourselves multiple times, somewhere.

Thanks!

**Comment by zsweigart** [comment] 2020-09-11 19:26
Closing this as it seems to be resolved.  Please reopen if the issue persists.

**Closed by zsweigart** 2020-09-11 19:26 UTC
Labels: android
