### ISSUE TITLE
React native web doesn't work with 10.6.0

### ISSUE THREAD

**Issue by b0n1q** [plaid/react-native-plaid-link-sdk#564] opened 2023-10-02 19:51 UTC
# The problem

React native web issue doesn't work with 10.6.0

# Environment

| Plaid Link React Native          | e.g. 10.6.0                                     

# Expected Result
no errors

# Screenshots
<img width="680" alt="image" src="https://github.com/plaid/react-native-plaid-link-sdk/assets/26281760/3d6f73bf-9455-4c78-8489-e03822feb14f">

**Comment by dtroupe-plaid** [comment] 2023-10-02 20:16
@b0n1q thanks for reporting the issue. Please provide all the information requested in the template otherwise we will not be able to provide support and this issue will be closed. 

It's particularly important that you describe in detail, provide all the environment information, and steps to reproduce. 

# The problem

Briefly describe the issue you are experiencing. Tell us what you were trying to do and what happened instead. 

# Environment

|                                                  |                                                                                  |
| -----------------------------| ----------------------------------------------- |
| Plaid Link React Native          | e.g. 10.3.0                                                                 |
| ReactNative Version               | e.g. 0.67.0                                                                 |
| Occurs on Android                  | e.g. yes                                                                     |
| Android OS Version                 | e.g. 11.0.0 (30)                                                         |
| Android Devices/Emulators    | e.g. Pixel 7a physical                                                |
| Occurs on iOS                          | e.g. yes                                                                     |
| iOS Version                               | e.g. 16                                                                       |
| iOS Devices/Emulators            | e.g. iPhone 14 Pro                                                    |
| Link Session ID                         | e.g. 0de00328-44f8-4c2e-9eaf-726b2f70169c |

# Steps to Reproduce

If necessary, describe the problem you have been experiencing in more detail.
Please include the configuration you are using for Link (excluding your keys
and personally identifiable information)

**Comment by b0n1q** [comment] 2023-10-03 09:25
# The problem
just install the library and open in Web
 
# Environment
Plaid Link React Native	e.g. 10.6.0
ReactNative Version	e.g. 0.71.8
Occurs on Android	e.g. no
Occurs on iOS	e.g. no
Occurs on Web	e.g. YES
# Steps to Reproduce
just install the library and open in Web

**Comment by dtroupe-plaid** [comment] 2023-10-03 16:13
Hi @b0n1q the reason this occurs on `10.6.0` is because we are leveraging [native components](https://reactnative.dev/docs/native-components-ios). This is clearly the issue based on your screenshot `requireNativeComponent` is not supported on web (because it's an iOS/Android native view). This feature of RN is not supported on React Native Web. For more information please see [this issue](https://github.com/necolas/react-native-web/issues/507).

You have a few options:

1. Lock your integration at `10.5.0`. This isn't ideal because you'll miss all future updates, but it's very low lift.

2. Use our [Web SDK](https://github.com/plaid/react-plaid-link). You can checkout the [documentation here](https://plaid.com/docs/link/web/).

4. You can use this SDK locally and strip all of the native component code (everything related to EmbeddedLink). Files would include [EmbeddedLinkView.tsx](https://github.com/plaid/react-native-plaid-link-sdk/blob/master/src/EmbeddedLink/EmbeddedLinkView.tsx), [NativeEmbeddedLinkView.tsx](https://github.com/plaid/react-native-plaid-link-sdk/blob/master/src/EmbeddedLink/NativeEmbeddedLinkView.tsx), [PLKEmbeddedViewManager.swift](https://github.com/plaid/react-native-plaid-link-sdk/blob/master/ios/PLKEmbeddedViewManager.swift), [PLKEmbeddedView.swift](https://github.com/plaid/react-native-plaid-link-sdk/blob/master/ios/PLKEmbeddedView.swift), [PLKEmbeddedView.m](https://github.com/plaid/react-native-plaid-link-sdk/blob/master/ios/PLKEmbeddedView.m), [PLKEmbeddedView.kt](https://github.com/plaid/react-native-plaid-link-sdk/blob/master/android/src/main/java/com/plaid/PLKEmbeddedView.kt), & [PLKEmbeddedViewManager.kt](https://github.com/plaid/react-native-plaid-link-sdk/blob/master/android/src/main/java/com/plaid/PLKEmbeddedViewManager.kt). You might get away this just being able to delete the typescript files and the corresponding exports, but I am not sure. 

I am closing this issue because this SDK is for React Native and not React Native Web.

**Closed by dtroupe-plaid** 2023-10-03 16:13 UTC
Labels: Needs Information

**Comment by b0n1q** [comment] 2023-10-03 16:14
> Hi @b0n1q the reason this occurs on `10.6.0` is because we are leveraging [native components](https://reactnative.dev/docs/native-components-ios). This is clearly the issue based on your screenshot `requireNativeComponent` is not supported on web (because it's an iOS/Android native view). This feature of RN is not supported on React Native Web. For more information please see [this issue](https://github.com/necolas/react-native-web/issues/507).
> 
> You have a few options:
> 
> 1. Lock your integration at `10.5.0`. This isn't ideal because you'll miss all future updates, but it's very low lift.
> 2. Use our [Web SDK](https://github.com/plaid/react-plaid-link). You can checkout the [documentation here](https://plaid.com/docs/link/web/).
> 3. You can use this SDK locally and strip all of the native component code (everything related to EmbeddedLink). Files would include [EmbeddedLinkView.tsx](https://github.com/plaid/react-native-plaid-link-sdk/blob/master/src/EmbeddedLink/EmbeddedLinkView.tsx), [NativeEmbeddedLinkView.tsx](https://github.com/plaid/react-native-plaid-link-sdk/blob/master/src/EmbeddedLink/NativeEmbeddedLinkView.tsx), [PLKEmbeddedViewManager.swift](https://github.com/plaid/react-native-plaid-link-sdk/blob/master/ios/PLKEmbeddedViewManager.swift), [PLKEmbeddedView.swift](https://github.com/plaid/react-native-plaid-link-sdk/blob/master/ios/PLKEmbeddedView.swift), [PLKEmbeddedView.m](https://github.com/plaid/react-native-plaid-link-sdk/blob/master/ios/PLKEmbeddedView.m), [PLKEmbeddedView.kt](https://github.com/plaid/react-native-plaid-link-sdk/blob/master/android/src/main/java/com/plaid/PLKEmbeddedView.kt), & [PLKEmbeddedViewManager.kt](https://github.com/plaid/react-native-plaid-link-sdk/blob/master/android/src/main/java/com/plaid/PLKEmbeddedViewManager.kt). You might get away this just being able to delete the typescript files and the corresponding exports, but I am not sure.
> 
> I am closing this issue because this SDK is for React Native and not React Native Web.

yeah, thanks I did lock 10.5.0 and it works

**Comment by dtroupe-plaid** [comment] 2023-10-11 20:49
@b0n1q this is resolved in 10.6.3

**Comment by b0n1q** [comment] 2023-10-12 10:45
> @b0n1q this is resolved in 10.6.3

thanks

**Comment by b0n1q** [comment] 2023-10-12 10:45
thanks!
