### ISSUE TITLE
react-native-plaid-link-sdk Error (Android)

### ISSUE THREAD

**Issue by sen2ran** [plaid/react-native-plaid-link-sdk#8] opened 2019-11-27 05:04 UTC
After installing and config  to android , The app is not getting started 

`

Could not determine the dependencies of task ':react-native-plaid-link-sdk:compileDebugAidl'.
> Could not resolve all task dependencies for configuration ':react-native-plaid-link-sdk:debugCompileClasspath'.
   > Could not find com.facebook.react:react-native:0.61.3.
     Required by:
         project :react-native-plaid-link-sdk

`

**Comment by sandeepg1220** [comment] 2019-12-02 07:02
I'm also facing same issue while running in android. Please help me to resolve.
Thanks in advance.

**Comment by JeffKGabriel** [comment] 2019-12-02 17:28
i believe it is caused by the specific version dependency `implementation 'com.facebook.react:react-native:0.61.3'` in the build.gradle

looking into some work arounds - most libs use - `implementation 'com.facebook.react:react-native:+'` but that causes some other issues for me currently

**Comment by zachrnolan** [comment] 2019-12-02 19:55
Also getting this error when running on 0.61.4.

**Comment by zsweigart** [comment] 2019-12-02 20:09
Thanks for the report, we will be moving to `implementation 'com.facebook.react:react-native:+'` in the next release which will also upgrade to the next release of the Android native sdk.  

@JeffKGabriel what issue are you running into with that implementation version?

**Comment by zachrnolan** [comment] 2019-12-02 21:32
@zsweigart After changing to `implementation 'com.facebook.react:react-native:+'`, I received an error due to my `minSdkVersion` being lower than what was set in react-native-plaid-link-sdk. I fixed this by raising my own projects `minSdkVersion` to 21.

When looking at other open source projects like `react-native-onesignal`, they will try to use the rootProject minSdkVersion or fall back to a default. Might be worth considering for this project.

```
def safeExtGet(prop, fallback) {
    rootProject.ext.has(prop) ? rootProject.ext.get(prop) : fallback
}

defaultConfig {
    minSdkVersion safeExtGet('minSdkVersion', 16)
}
```

Also, any ETA on the next release? Thanks!

**Comment by zsweigart** [comment] 2019-12-03 01:38
This sdk is a wrapper around the native android sdk which has a `minSdkVersion` of 21.  We decided on this version as it supports 89.3% of users worldwide; however, in our primary markets (U.S., Canada, and several countries in Europe) it's closer to 97%.  Additionally, the Android developer experience is drastically better between `minSdkVersion` of 21 vs 19.  We will update the documentation that the `minSdkVersion` is 21 for this SDK.

The ETA for the next update is before December 15th.

**Comment by zachrnolan** [comment] 2019-12-03 01:47
I agree that minSdkVersion 21 is the way to go. Thanks for the update!

**Comment by sen2ran** [comment] 2019-12-03 05:32
> I'm also facing the same issue while running in android. Please help me to resolve.
> @sen2ran Do you get any solution?.
> Thanks in advance.

still i didn't get any solution

**Comment by zsweigart** [comment] 2019-12-16 17:48
You will either have to point to 'com.facebook.react:react-native:0.61.3' in your build.gradle file and  set the dependency version for React Native to 0.61.3 in your package.json file then run `npm install` or update to the latest version of the sdk which is dependent on the latest version. 

Just as a heads up we will be releasing a new version later today with some small api improvements as well.

**Comment by wkiefer** [comment] 2019-12-17 00:38
This should be fixed as of https://github.com/plaid/react-native-plaid-link-sdk/releases/tag/v2.0.1

**Closed by wkiefer** 2019-12-17 00:38 UTC
