### ISSUE TITLE
PlaidLink not working in IOS 13 version.

### ISSUE THREAD

**Issue by Dhaval1905** [plaid/react-native-plaid-link-sdk#544] opened 2023-08-08 06:46 UTC
PlaidLink not working in IOS 13 version. I have used PlaidLink sdk but is not working in IOS version 13. Would you please look into it as soon as you can.

Device info:-
Iphone 11.
IOS version :- 13.0

Error response:- 

{"error": {"displayMessage": "", "errorCode": "", "errorDisplayMessage": "", "errorMessage": "", "errorType": ""}, "metadata": {"institution": {"id": "", "name": ""}, "linkSessionId": "1adcd445-71ef-4287-9405-76b3c4a5fa4c", "metadataJson": "", "requestId": "", "status": ""}}

**Comment by dtroupe-plaid** [comment] 2023-08-08 16:06
@Dhaval1905 again you did not provide any details on what the issue is. You have a session ID so Link must be launching, but you did not provide any details on what specifically is not working. 

Can you please provide the following to help me help you:

1. An explanation of what "is not working in IOS version 13" means? Please be as specific as possible. 
2. Steps to reproduce the issue. 

Again without this information we cannot provide assistance and this issue will be closed. 

Thanks!

**Comment by dtroupe-plaid** [comment] 2023-08-08 22:04
@Dhaval1905 I was able to reproduce the issue on iOS 13.0. However, I was not able to reproduce the issue on iOS 13.4 or 13.7 so this is likely only impacting a small percentage of traffic. The issue occurs outside of this SDK (server-side), as such I am going to close this issue. However, I will post an update once I get some information about the server-side update. 


Sample error 

```json
{
  "fetch_id" : "da295d4d-129f-4eeb-8db9-26a691b19a2b",
  "messages" : [
    {
      "event" : {
        "event_name" : "RUNTIME_ERROR"
      },
      "message_id" : "5bbbd5f8-1f77-47cf-b457-fcd7751d76b5",
      "timestamp" : "2023-08-08T21:45:56.513950222Z"
    },
    {
      "result" : {
        "callback" : "SDK_RESULT_CALLBACK_ERROR",
        "metadata_json" : "{\"link_session_id\":\"8f755826-b5b6-40f4-9416-a3678bf3a030\",\"status\":\"\",\"request_id\":\"\"}",
        "metadata" : {
          "link_session_id" : "8f755826-b5b6-40f4-9416-a3678bf3a030"
        }
      },
      "message_id" : "2b80c38c-91ce-4cd5-8ff8-e1335b819d7c",
      "timestamp" : "2023-08-08T21:45:56.516001548Z"
    },
    {
      "event" : {
        "metadata_json" : "{\"error_code\":\"\",\"error_message\":\"\",\"error_type\":\"\",\"exit_status\":\"\",\"institution_id\":\"\",\"institution_name\":\"\",\"institution_search_query\":\"\",\"request_id\":\"qgCjOdMDNtT71nZ\",\"link_session_id\":\"8f755826-b5b6-40f4-9416-a3678bf3a030\",\"mfa_type\":\"\",\"view_name\":\"CONSENT\",\"timestamp\":\"\",\"selection\":\"\",\"brand_name\":\"\",\"match_reason\":\"\",\"routing_number\":\"\",\"account_number_mask\":\"\",\"view_variant\":\"\",\"is_update_mode\":\"\"}",
        "event_name" : "TRANSITION_VIEW",
        "metadata" : {
          "request_id" : "qgCjOdMDNtT71nZ",
          "view_name" : "CONSENT",
          "link_session_id" : "8f755826-b5b6-40f4-9416-a3678bf3a030"
        }
      },
      "message_id" : "b3dfb756-ef29-408d-97e4-a3268888794c",
      "timestamp" : "2023-08-08T21:45:56.435757795Z"
    }
  ]
}
```

Thanks

**Closed by dtroupe-plaid** 2023-08-08 22:04 UTC
